### ISSUE TITLE
UMLS: package utilities isn't available any more

### ISSUE THREAD

**Issue by SoRr0wW** [text-machine-lab/CliNER#14]
In order to use the UMLS subsets, after the database is build I get an error that the module utilities can't be loaded. But I can't install it, cause it seems abandoned. I have a link to a stackoverflow post:
[https://stackoverflow.com/questions/44143332/issues-while-installing-utilities-module-in-python](url)

As you can see the official page for the package, also doesn't show that it nether can be installed through pip nor download the source files. Link below.
[https://pypi.org/project/utilities/](url)

This situation is really weird cause even if you take a package out of the repository you have to provide an alternative. But I didn't see an alternative when browsing through similar packages.

It would be nice if anyone take on this issue and make UMLS possible with CliNER again.

**Comment by yaronv** [comment]
I replaces this "utilities" with importing the utils file which exist in the parent folder and it works fine
