### ISSUE TITLE
Tokenization question

### ISSUE THREAD

**Issue by ZhaofengWu** [text-machine-lab/CliNER#17]
If we want to use the out-of-the-box silver model to do prediction, what tokenization scheme is expected? NLTK `word_tokenize`? Or should I use the tools/tok.py file?

**Comment by tnaumann** [comment]
The `tools/tok.py` relies on `nltk.sent_tokenize` in part, but includes some additional considerations for things like the i2b2 format, which typically includes whitespace-separated tokens with one sentence per line.
