### ISSUE TITLE
format.py not working

### ISSUE THREAD

**Issue by oderuyver** [text-machine-lab/CliNER#21]
I would like to use the format.py script to convert i2b2 files to xml format. 
I think that this script still needs to be changed. It is importing notes.Note which doesn't exist in this repo.

**Comment by oderuyver** [comment]
```
-sh-4.2$ python format.py -txt data/examples/data.txt -annotations data/test_predictions/data.con -out data/test_predictions/ -format xml
Traceback (most recent call last):
  File "format.py", line 15, in <module>
    from notes.note import Note
ModuleNotFoundError: No module named 'notes.note'
```

**Comment by pruksmhc** [comment]
Has this been resolved?

**Comment by tnaumann** [comment]
It has not, but the `Note` class that's being referenced can be found in commits prior to c824b8896633eae4c7d3bc2d32f36ff6d2ebbdd2 (see: `git grep "class Note" $(git rev-list --all)`).
