### ISSUE TITLE
UMLS utility

### ISSUE THREAD

**Issue by saitejagajulapeta** [text-machine-lab/CliNER#23]
The predictions are same irrespective of whether UMLS tables are used or not.
I don't know  if we need to do anything else other than 

1) download UMLS tables into a $CLINER/umls_tables directory
2) change the config.txt file in $CLINER 
      UMLS $CLINER/umls_tables    instead of UMLS None

If anybody can share how to fix this issue it will be really helpful!
Thank you in advance!!!

**Comment by Rajeev-Doxper** [comment]
use python 2

**Comment by Rajeev-Doxper** [comment]
> The predictions are same irrespective of whether UMLS tables are used or not.
> I don't know if we need to do anything else other than
> 
> 1. download UMLS tables into a $CLINER/umls_tables directory
> 2. change the config.txt file in $CLINER
>    UMLS $CLINER/umls_tables    instead of UMLS None
> 
> If anybody can share how to fix this issue it will be really helpful!
> Thank you in advance!!!

use python2

**Comment by tnaumann** [comment]
Issue #22 identified an issue with `get_cui` that returned `[]` for all words other than `"blood"`. This was commented out in 854dd83d2bffb7ba2aaea1af623b85ccf2a0af7b.
