### ISSUE TITLE
Cliner is not recognized

### ISSUE THREAD

**Issue by ManasaVeenaKarri** [text-machine-lab/CliNER#24]
I have followed all the steps in the readme but after installation, I am getting ''cliner' is not recognized as an internal or external command. How can i use the cliner? Also, cliner is unrecognizable format. Is there any way i can use the cliner tool? Please provide the detailed approach

**Comment by mwedzi** [comment]
You can pass the cliner file directly to python, as it is just a python script file. For example:
python cliner predict ...

**Comment by kaddynator** [comment]
Can you update the readme script ? 

Change the command to start with "python"

**Comment by tnaumann** [comment]
This appears to have been done previously.
