### ISSUE TITLE
Directly interacting with code examples

### ISSUE THREAD

**Issue by demongolem** [text-machine-lab/CliNER#25]
I was wondering if some getting started examples could be added that would directly call functions instead of running modules from the command line.  Also, it would be helpful to know about the general design philosophy if it is intended to have people call from the command line.  I think it was Rasa which made the decision when it went to v 1.0 to go from programmatic access to command-line only access making it very hard to call anything from within one's own code.

**Comment by tnaumann** [comment]
Thank you for the feedback. Getting started examples would be excellent and we'll look forward to contributions in this area.
