### ISSUE TITLE
Unable to run lstm model successfully

### ISSUE THREAD

**Issue by Ketki-Savle** [text-machine-lab/CliNER#26]
Below is the command I am trying:

$ python cliner train --txt "data/i2b2/*.txt" --annotations "data/i2b2/*.con" --format i2b2 --model models/i2b2_lstm.model --use-lstm

Here is the trace: 

NO DEV
IN ERROR CHECK
0.1
	Creating 90/10 train/dev split
	vectorizing words all
TESTING NEW DATSET OBJECT
Traceback (most recent call last):
  File "cliner", line 60, in <module>
    main()
  File "cliner", line 49, in main
    train.main()
  File "/Users/ag33366/CliNER/code/train.py", line 155, in main
    train(training_list, args.model, args.format, args.use_lstm, logfile=args.log, val=val_list, test=test_list)
  File "/Users/ag33366/CliNER/code/train.py", line 187, in train
    model.train(train_docs, val=val_docs, test=test_docs)
  File "/Users/ag33366/CliNER/code/model.py", line 199, in train
    test_sents=test_sents, test_labels=test_labels)
  File "/Users/ag33366/CliNER/code/model.py", line 253, in train_fit
    dev_split=dev_split     )
  File "/Users/ag33366/CliNER/code/model.py", line 382, in generic_train
    dataset = Exp.Dataset()
NameError: name 'Exp' is not defined

I am able to run the crf model successfully but having issues with LSTM. Could you please reply as soon as possible. Thank you.

**Comment by tompollard** [comment]
@Ketki-Savle the chunk of code that is bugging is: https://github.com/text-machine-lab/CliNER/blob/70fd8e5cd888f8cbb66913965e277c264984f124/code/model.py#L382

It looks like `Exp.Dataset()` is trying to create an instance of the Dataset class at: https://github.com/text-machine-lab/CliNER/blob/70fd8e5cd888f8cbb66913965e277c264984f124/code/DatasetCliner_experimental.py#L70

The only import for `DatasetCliner_experimental` is in an `if` clause in another method ("`ClinerModel`"), which I assume is getting skipped (not looked into details).

Perhaps try moving all of the imports at https://github.com/text-machine-lab/CliNER/blob/70fd8e5cd888f8cbb66913965e277c264984f124/code/model.py#L148 to the top of `model.py`.

**Comment by Ketki-Savle** [comment]
Hello, 

I actually moved that statement at the beginning with all import statements and it worked. Your observation is correct, that if loop was probably not importing all those statements correctly. 

Thank you. 

-Ketki

**Comment by tompollard** [comment]
Glad to hear that worked! If you have the chance, please could you make a pull request to the repo, so that the fix can be merged? No problem if you'd prefer not to...I expect someone will get to it later :)
